### ISSUE TITLE
Add decrypt_with_ttl to support passing TTL on decryption

### ISSUE THREAD

**Issue by alex** [mozilla-services/fernet-rs#11]

**Comment by alex** [comment]
@bbangert Is this a requirement for your use case, or can this be done "whnenever someone finally needs it"? The core code supports it, so the implementation will be about 3 LoC, but I'm feeling lazy about writing tests :-)

**Comment by bbangert** [comment]
We aren't using TTL's with fernet, so its not a priority or necessity for us.

**Comment by alex** [comment]
:+1:

**Comment by Firstyear** [comment]
I've just added a PR for this, because I need the TTL functionality for a project that I'm working on :)

**Comment by Firstyear** [comment]
You can close this issue now since the PR was merged!
