### ISSUE TITLE
Add documentation with examples

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/fernet-rs#17]
Before publishing on crates.io, full documentation strings for public functions should be added with examples that are doc-tested. A package-level set of basic docs should be included as well.

**Comment by alex** [comment]
Docs for multifernet are probably the next thing to add.

**Comment by Firstyear** [comment]
Since I'm going to start using fernet more soon I might be able to spend an hour or two on improving your documentation soon.

**Comment by Firstyear** [comment]
@bbangert I think this can be closed now?

**Comment by bbangert** [comment]
Yep, believe so! Thanks for the docs!
