### ISSUE TITLE
Expose decrypt_at_time and encrypt_at_time functions

### ISSUE THREAD

**Issue by Firstyear** [mozilla-services/fernet-rs#36]
In a project where I plan to use fernet, I would like to be able to assert certain behaviours of expiry with time stamps. To test this effectively, it would be great to be able to pass in the encrypt_at_time and decrypt_at_time so that in my test suites I am able to provide mock timestamps to assert correct behaviours of my integration with expired tokens etc. As much as I trust your code to do the right thing with expiry, I want to be sure my project does too!

To do this, I need the decrypt_at_time and encrypt_at_time functions exposed so that I can pass in the mock timestamps, and in production, I pass in the systemtime::now() instead. 

Would there be any objections to me making these function pub?

**Comment by bbangert** [comment]
I don't have any objections to this offhand, they should probably be labeled with doc strings that they're intended for use with tests though.

@alex Are these functions in danger of being misused if they're exposed as a public API?

**Comment by alex** [comment]
The use case for testing is pretty clear IMO.

Perhaps we could expose them behind a `cfg()` that people could use only in tests or something?

The way you could misuse it would be specifying the time incorrectly, and as a result decrypt things that should be treated as expired.

**Comment by Firstyear** [comment]
cfg(test) doesn't propogate out though, so you'd need to use a feature flag to enable them I guess?

**Comment by Firstyear** [comment]
https://github.com/mozilla-services/fernet-rs/pull/39
