### ISSUE TITLE
Update crates.io

### ISSUE THREAD

**Issue by Firstyear** [mozilla-services/fernet-rs#40]
The code in the repo is at 0.1.3 (after the fernet_danger_timestamp feature is added). It would be great for this to be updated on crates.io which is still listed as version 0.1.0 so that these changes can be used externally.

Thanks!

**Comment by Firstyear** [comment]
Probably worth waiting on #17 before this is done

**Comment by Firstyear** [comment]
@bbangert @alex ping on this issue.

**Comment by bbangert** [comment]
0.1.3 has been published.

**Comment by Firstyear** [comment]
Thanks @bbangert! Really appreciate this. Please let me know if there are any other ways I can help with this crate in the future.

**Comment by Firstyear** [comment]
Sorry to be a pain, I just checked crates.io and it looks like this is missing the docs change from #17 - does this need to be republished (there are no code changes sinces), or does it need to move to v1.4 to get these? 

https://crates.io/crates/fernet

**Comment by bbangert** [comment]
Probably needs to move to 1.4 I'd assume. I did a fresh pull before publishing so I'm not sure why the docs wouldn't be included.
