### ISSUE TITLE
Update dependencies and release?

### ISSUE THREAD

**Issue by Firstyear** [mozilla-services/fernet-rs#57]
Hi there,

It's been over a year since the last release of this library. Is it possible to publish a 1.4? At the moment I'm having to rely on git refs for my dependency specifications of this. 

Thanks,

**Comment by Firstyear** [comment]
Reminder @bbangert @pjenvey @jrconlin - It would be good to have a release of this project for crates.io.

**Comment by jrconlin** [comment]
Thanks. Sorry, I need to add this project to my calendar.

**Comment by jrconlin** [comment]
Published [0.1.4](https://crates.io/crates/fernet/0.1.4)
