### ISSUE TITLE
Why same starting characters in every encrypted string?

### ISSUE THREAD

**Issue by lermana** [mozilla-services/fernet-rs#82]
Hello, in using this library for some encryption tasks, I've noticed that the resultant encrypted strings all start with the same characters. Here's an MRE:

```
#[cfg(test)]
mod tests {

    use fernet::Fernet;

    #[test]
    fn test_encryption() {

        let plaintext = "secret".to_string();
        let plaintext_in_binary = plaintext.clone().into_bytes();
        let plaintext_array = plaintext_in_binary[..].try_into().unwrap();

        // take 1
        let key = Fernet::generate_key();
        println!("Key 1: {}", &key);

        let fernet = Fernet::new(&key).unwrap();
        let encrypted1 = fernet.encrypt(plaintext_array);
        println!("First try! ... {}", &encrypted1);

        // take 2
        let key = Fernet::generate_key();
        println!("Key 2: {}", &key);

        let fernet = Fernet::new(&key).unwrap();
        let encrypted2 = fernet.encrypt(plaintext_array);
        println!("Second try! ... {}", &encrypted2);

        assert_eq!(encrypted1[0..11], encrypted2[0..11]);

        // check decryption
        let decrypted = String::from_utf8(fernet.decrypt(&encrypted2)
                                    .expect("Couldn't decrypt key"))
                                    .expect("Couldn't cast key bytes as String");

        assert_eq!(plaintext, decrypted);

    }

}
```

here's the output I get:
```
running 1 test
Key 1: dT6hbM4eEwkv7SVEHIqGC1AjvOI-O9d-AFpOiI194Tg=
First try! ... gAAAAABkg00uBid18loakPF08JsuZadDi4kF6iW8tACWxvboamIrlWQqrjSWP0Optr2bXjaT4ge1bek4OeVjmVuMnM7Xc_R1Nw==
Key 2: mtr0TYFXOXnzpxonTcnWWpY22p9f1c3KO6cLlkoRi7k=
Second try! ... gAAAAABkg00ur5W0zACyEgPG-kfE0XlxMI5wpgGfuCm33JN635OiynJt5k5KoNhCre0TX00JPGoVW9dMrcX0y_EMhEkokYqXWg==
test tests::test_encryption ... ok
```

Notice the `gAAAAABkg0` in front of both ... I can run that test over and over again and it works. Even in a totally different environment, where I am actually putting a random and unique salt in with every encrypted string, I still get at least `gAAAAABk` in front. I'm wondering if that's due to the clock component in `_encrypt_from_parts`? If so, could you possibly explain what that bit is there? And if not, maybe there's something else going on.

Much appreciate your thoughts,

Abe

**Comment by alex** [comment]
The initial handful of bytes in a fernet ciphertext are from the version, which is cosntant, and a timestamp (https://github.com/mozilla-services/fernet-rs/blob/master/src/lib.rs#L186-L190). Because the majority of the bytes in a timestamp don't change, the initial bytes in the output will also tend to be the same. If you calling encrypt 2x in a row, I'd expect only the very last byte to vary.

**Comment by lermana** [comment]
DUH, right there in the code.... very helpful - thanks. I was worried about having a timestamp (a known, somewhat-unchanging thing) out there in lots of ciphertexts, although if the timestamp (or the front part of it, at least) shows up the same in different ciphertexts, it's obviously not actually being encrypted so there's no issue.
